server:
  port: 8087
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/firstproject_db
    username: postgres
    password: postgres

  sql:
    init:
      data-locations: classpath:data.sql

  security:
    user:
      name: seoin
      password: 123qwe
      roles: ADMIN


logging:
  level:
    org.hibernate:
      sql: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

business:
  url: https://api.odcloud.kr/api/nts-businessman/v1/status?serviceKey=
  encoding: XNM%2FAHJB%2B68HV79cSGOQ%2BDtMs87Gq3gmewT2NdPV8a2uH1uwWaF2k3L1CjEypfOMtotlgr%2FG%2BYhyNtDU8DxZuw%3D%3D
  decoding: XNM/AHJB+68HV79cSGOQ+DtMs87Gq3gmewT2NdPV8a2uH1uwWaF2k3L1CjEypfOMtotlgr/G+YhyNtDU8DxZuw==


address:
  url: https://www.juso.go.kr/addrlink/addrLinkApi.do
  key: devU01TX0FVVEgyMDI0MDQwNzIxNDYzMDExNDY2OTM=

  security: